language: php
sudo: required
dist: bionic

addons:
  mariadb: '10.3'
  hosts:
    - moodle.test
  firefox: latest
  apt:
    packages:
      - redis-server

services:
  - memcached
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - IGNORE_PATHS=vendor,source
    - IGNORE_NAMES=*.txt,*.md

# Alternate tests with MySQL and PostgreSQL
matrix:
  include:
    - php: 7.3
      env: DB=mariadb MOODLE_BRANCH=MOODLE_38_STABLE plgdir=moodle/availability/condition/ipaddress
    - php: 7.3
      env: DB=mariadb MOODLE_BRANCH=MOODLE_38_STABLE plgdir=moodle/mod/jitsi

before_install:
  - phpenv config-rm xdebug.ini
  - mv $plgdir/* .
  - rm -rf moodle
  - cd ../..
  - nvm install 8.9;
    nvm use 8.9;
    composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
install:
  - moodle-plugin-ci install
  #- echo '$CFG->cookiesecure = false;' >> moodle/config.php

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || false
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
